<?php

//  $xml_post_url = "https://gxbo-thailand-hr.appspot.com/submit_xml";
  $xml_post_url = "http://webiz.co.th/sites/crm.webiz.co.th/modules/crm/post.php";
  $secret_key = "90c6a0f677fc4fc7bff9c87cb325eb30";

  // create XML payload
  $xml_payload = '<?xml version="1.0" encoding="utf-8"?>
<businesses secret-key="'.$secret_key.'"><!-- this key is only valid for gxbo-test.appspot.com -->

<business format-version="2.0-spain">
  <partner-reference>UK-7426567c1a5147529cd1c5ed7caa288e</partner-reference><!-- country code followed by UUID generated by partner in case there are multiple submissions of the same user -->
  <sign-up-date>20101013T181830Z</sign-up-date><!-- ISO 8601:1988 format, specifically: [YYYY][MM][DD]T[hh][mm]Z -->

  <given-name>Joe</given-name>
  <family-name>Bloggs</family-name>
  <email>joe@bloggs.com</email>
  <language>fr</language><!-- ISO 639 language codes -->

  <final-url>http://www.joescakes.com</final-url>
  <temporary-url>http://joescakes.partner.com/yummycakes</temporary-url>
  <final-url-being-used>False</final-url-being-used>

  <business-name>Blog cakes</business-name>
  <business-description>Very expensive cakes for rich people.</business-description><!-- A description of the business. Do not include tabs, extra lines or carriage returns. (Maximum 200 characters) -->
  <market-segments>
    <segment>Cake Shop</segment>
    <segment>Retail</segment>
  </market-segments>

  <address>
    <address-line-1>123 Road Street</address-line-1>
    <address-line-2>Somewhere</address-line-2><!-- can be empty -->
    <city>Nottingham</city>
    <state>Nottinghamshire</state>
    <region>East Midlands</region>
    <post-code>AB12 3CD</post-code>
    <country-code>UK</country-code><!-- ISO 3166-1-alpha-2 -->
  </address>

  <opt-in-email>True</opt-in-email>
  <opt-in-post>True</opt-in-post>
  <opt-in-places>True</opt-in-places>

  <account-deleted>False</account-deleted>

  <spain-cif>123456</spain-cif>
  <spain-nif>123456</spain-nif>
  <spain-web-created>1</spain-web-created>
  <spain-acquisition-channel>10014</spain-acquisition-channel>

</business>

</businesses>';

  //echo $xml_payload ; //exit;
  $ch = curl_init();
  curl_setopt($ch, CURLOPT_URL, $xml_post_url);
  curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
  curl_setopt($ch, CURLOPT_TIMEOUT, 10);
  curl_setopt($ch, CURLOPT_HEADER, true);
  //curl_setopt($ch, CURLOPT_HTTPHEADER, Array("Content-Type: text/xml"));
  curl_setopt($ch, CURLOPT_POST, 1);
  curl_setopt($ch, CURLOPT_POSTFIELDS, 'business='.$xml_payload);
  //curl_setopt($ch, CURLOPT_SSLVERSION,3);
  //curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, FALSE);
  //curl_setopt($ch, CURLOPT_SSL_VERIFYHOST,  2);

$result = curl_exec($ch);
echo $result;
?>
